spring:
  application:
    name: CompanyMicroservice

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://postgres-company:5432/companydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



  # RabbitMQ Configuration
  rabbitmq:
    host: rabbitmq  # Docker service name
    port: 5672
    username: guest
    password: guest

server:
  port: 8088

# Keycloak Configuration
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://keycloak:8080/realms/MicroserviceSPM
        jwk-set-uri: http://keycloak:8080/realms/MicroserviceSPM/protocol/openid-connect/certs