spring:
  application:
    name: MicroServiceLogin

  datasource:
    url: jdbc:postgresql://postgres-db:5432/login_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/MicroserviceSPM
          # jwk-set-uri: http://keycloak:8080/realms/MicroserviceSPM/protocol/openid-connect/certs
          # Si usas issuer-uri, no es necesario jwk-set-uri

server:
  port: 8085

keycloak:
  auth-server-url: http://keycloak:8080
  realm: MicroserviceSPM
  resource: system-desktop
  credentials:
    secret: system-secret