server:
  port: 8081

spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      routes:
        - id: project-service
          uri: http://localhost:8086
          predicates:
            - Path=/apiProject/**
        - id: postulation-service
          uri: http://localhost:8082
          predicates:
            - Path=/postulaciones/**
        - id: company-service
          uri: http://localhost:8088
          predicates:
            - Path=/apiCompanies/**
        - id: student-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/Students/**
        - id: login-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/usuarios/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MicroserviceSPM
          jwk-set-uri: http://localhost:8080/realms/MicroserviceSPM/protocol/openid-connect/certs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

