package co.edu.unicauca.view;

import co.edu.unicauca.domain.entities.Company;
import co.edu.unicauca.domain.entities.Project;
import co.edu.unicauca.domain.entities.User;
import co.edu.unicauca.domain.services.CompanyService;
import co.edu.unicauca.domain.services.ProjectService;
import co.edu.unicauca.infra.IFrameEventListener;
import co.edu.unicauca.infra.Messages;
import co.edu.unicauca.infra.gotaAguaTexto;
import co.edu.unicauca.infra.validation.ValidationContext;
import co.edu.unicauca.infra.validation.Validator;
import co.edu.unicauca.infra.validation.strategies.DateValidationStrategy;
import co.edu.unicauca.infra.validation.strategies.EmailValidationStrategy;
import co.edu.unicauca.infra.validation.strategies.NotEmptyAndNotDefaultStrategy;
import co.edu.unicauca.infra.validation.strategies.NumericDecimalValidationStrategy;
import co.edu.unicauca.infra.validation.strategies.NumericValidationStrategy;
import co.edu.unicauca.infra.validation.strategies.TextOnlyValidationStrategy;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author evers
 */
public class GUIPostularProject extends javax.swing.JDialog {

    /**
     * Creates new form GUIPostularProject
     */
    private IFrameEventListener listener;
    private ProjectService projectService;
    private CompanyService companyService;
    private User user;
    private ValidationContext nombreValidator;
    private ValidationContext resumenValidator;
    private ValidationContext descripcionValidator;
    private ValidationContext objetivoValidator;
    private ValidationContext tiempoValidator;
    private ValidationContext presupuestoValidator;
    private ValidationContext fechaValidator;

    public GUIPostularProject(JFrame parent, ProjectService projectService, IFrameEventListener listener, User user, CompanyService companyService) {
        super(parent, "Nueva projecto", true);
        this.user = user;
        this.projectService = projectService;
        this.companyService = companyService;
        this.listener = listener;
         configurarValidadores();
        initComponents();
        setSize(800, 700);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbProjectName = new javax.swing.JLabel();
        lbOverView = new javax.swing.JLabel();
        lbDescription = new javax.swing.JLabel();
        lbObjetive = new javax.swing.JLabel();
        lbMaximumTime = new javax.swing.JLabel();
        lbEstimatedBudge = new javax.swing.JLabel();
        lbEstimatedDeliveryDate = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        txtNameProyect = new gotaAguaTexto("project name");
        txtOverView = new gotaAguaTexto("overView");
        txtDescription = new gotaAguaTexto("description");
        txtObjetivo = new gotaAguaTexto("objective");
        txtMaximumTime = new gotaAguaTexto("maximum time");
        txtEstimatedBudge = new gotaAguaTexto("estimated budget");
        txteEstimatedDeliveryDate = new gotaAguaTexto("estimated delivery date");
        btnRegistrarProyecto = new javax.swing.JButton();
        lbWarningProjectName = new javax.swing.JLabel();
        lbWarningDescription = new javax.swing.JLabel();
        lbWarningOverView = new javax.swing.JLabel();
        lbWarningObjetive = new javax.swing.JLabel();
        lbWarningMaximumTime = new javax.swing.JLabel();
        lbWarningEstimatedBudge = new javax.swing.JLabel();
        lbWarningEstimatedDeliveryDate = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(897, 509));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbProjectName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbProjectName.setForeground(new java.awt.Color(112, 112, 112));
        lbProjectName.setText("Nombre del proyecto");

        lbOverView.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbOverView.setForeground(new java.awt.Color(112, 112, 112));
        lbOverView.setText("Resumen");

        lbDescription.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDescription.setForeground(new java.awt.Color(112, 112, 112));
        lbDescription.setText("Descripción del proyecto");

        lbObjetive.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbObjetive.setForeground(new java.awt.Color(112, 112, 112));
        lbObjetive.setText("Objetivo principal");

        lbMaximumTime.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbMaximumTime.setForeground(new java.awt.Color(112, 112, 112));
        lbMaximumTime.setText("Tiempo maximo");

        lbEstimatedBudge.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbEstimatedBudge.setForeground(new java.awt.Color(112, 112, 112));
        lbEstimatedBudge.setText("Presupuesto estimado");

        lbEstimatedDeliveryDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbEstimatedDeliveryDate.setForeground(new java.awt.Color(112, 112, 112));
        lbEstimatedDeliveryDate.setText("Fecha de entrega esperada");

        txtTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(112, 112, 112));
        txtTitle.setText("Registrar nuevo proyecto");

        txtNameProyect.setText("project name");
        txtNameProyect.setActionCommand("<Not Set>");
        txtNameProyect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameProyectActionPerformed(evt);
            }
        });

        txtOverView.setText("overView");

        txtDescription.setText("description");

        txtObjetivo.setText("objective");
        txtObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObjetivoActionPerformed(evt);
            }
        });

        txtMaximumTime.setText("maximum time");

        txtEstimatedBudge.setText("estimated budget");

        txteEstimatedDeliveryDate.setText("estimated delivery date");

        btnRegistrarProyecto.setBackground(new java.awt.Color(9, 33, 103));
        btnRegistrarProyecto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProyecto.setText("Registrar");
        btnRegistrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProyectoActionPerformed(evt);
            }
        });

        lbWarningProjectName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbWarningProjectName.setForeground(new java.awt.Color(255, 51, 51));
        lbWarningProjectName.setText("*");
        lbWarningProjectName.setFocusable(false);

        lbWarningDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbWarningDescription.setForeground(new java.awt.Color(255, 51, 51));
        lbWarningDescription.setText("*");

        lbWarningOverView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbWarningOverView.setForeground(new java.awt.Color(255, 51, 51));
        lbWarningOverView.setText("*");

        lbWarningObjetive.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbWarningObjetive.setForeground(new java.awt.Color(255, 51, 51));
        lbWarningObjetive.setText("*");

        lbWarningMaximumTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbWarningMaximumTime.setForeground(new java.awt.Color(255, 51, 51));
        lbWarningMaximumTime.setText("*");

        lbWarningEstimatedBudge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbWarningEstimatedBudge.setForeground(new java.awt.Color(255, 51, 51));
        lbWarningEstimatedBudge.setText("*");

        lbWarningEstimatedDeliveryDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbWarningEstimatedDeliveryDate.setForeground(new java.awt.Color(255, 51, 51));
        lbWarningEstimatedDeliveryDate.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbEstimatedDeliveryDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbWarningEstimatedDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbEstimatedBudge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbWarningEstimatedBudge, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMaximumTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbWarningMaximumTime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbObjetive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbWarningObjetive, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbProjectName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbWarningProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbOverView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbWarningOverView, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(lbWarningDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEstimatedBudge, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaximumTime, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtObjetivo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOverView, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNameProyect, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txteEstimatedDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitle)
                    .addComponent(btnRegistrarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbProjectName)
                        .addGap(60, 60, 60)
                        .addComponent(lbOverView)
                        .addGap(55, 55, 55)
                        .addComponent(lbDescription)
                        .addGap(55, 55, 55)
                        .addComponent(lbObjetive)
                        .addGap(55, 55, 55)
                        .addComponent(lbMaximumTime)
                        .addGap(55, 55, 55)
                        .addComponent(lbEstimatedBudge)
                        .addGap(50, 50, 50)
                        .addComponent(lbEstimatedDeliveryDate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtOverView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbWarningOverView))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNameProyect, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbWarningProjectName))
                                .addGap(75, 75, 75)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningDescription))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningObjetive))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaximumTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningMaximumTime))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstimatedBudge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningEstimatedBudge))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txteEstimatedDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningEstimatedDeliveryDate))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProyectoActionPerformed

        limpiarWarnings();
        String nombre = txtNameProyect.getText().trim();
        String resumen = txtOverView.getText().trim();
        String descripcion = txtDescription.getText().trim();
        String objetivo = txtObjetivo.getText().trim();
        String tiempoMaximo = txtMaximumTime.getText().trim();
        String presupuesto = txtEstimatedBudge.getText().trim();
        String fechaEntregaEsperada = txteEstimatedDeliveryDate.getText().trim();

        boolean isValid = validarFormulario(nombre, resumen, descripcion,objetivo, tiempoMaximo, presupuesto, fechaEntregaEsperada);

        if (isValid) {
            Project project = new Project(String.valueOf(user.getId()), nombre, resumen,descripcion, objetivo, tiempoMaximo, presupuesto, fechaEntregaEsperada);
            project.setPeriodoAcademico(calcularPeriodo());
            if (projectService.saveProject(project)) {
                if (listener != null) {
                    listener.onEventTriggered();
                }
                Messages.showMessageDialog("Agregado correctamente", "Atención");
                this.dispose();
            } else {
                Messages.showMessageDialog("No se agregó el proyecto", "Atención");
            }
        }
    }//GEN-LAST:event_btnRegistrarProyectoActionPerformed
    public String calcularPeriodo() {
        LocalDate today = LocalDate.now();
        return today.getMonthValue() < 6 ? String.valueOf(today.getYear()) + "-" + 1 : String.valueOf(today.getYear()) + "-" + 2;
    }

    private boolean validarFormulario(String nombre, String resumen, String descripcion,String objetivo, String tiempoMaximo,String presupuesto, String fechaEntregaEsperada) {
        
        Map<ValidationContext, JTextField> campos = Map.of(nombreValidator, txtNameProyect,resumenValidator, txtOverView,descripcionValidator, txtDescription,
                objetivoValidator, txtObjetivo,tiempoValidator, txtMaximumTime,presupuestoValidator, txtEstimatedBudge,fechaValidator, txteEstimatedDeliveryDate);
        
        Map<ValidationContext, JLabel> advertencias = Map.of(nombreValidator, lbWarningProjectName,resumenValidator, lbWarningOverView,descripcionValidator, 
                lbWarningDescription,objetivoValidator, lbWarningObjetive,tiempoValidator, lbWarningMaximumTime,presupuestoValidator, lbWarningEstimatedBudge,fechaValidator, lbWarningEstimatedDeliveryDate
        );
        
        boolean allValid = true;
        for (Map.Entry<ValidationContext, JTextField> entry : campos.entrySet()) {
            ValidationContext validador = entry.getKey();
            JTextField campo = entry.getValue();
            
            if (!validador.executeValidation(campo.getText().trim())) {
                campo.requestFocus();
                mostrarAdv(advertencias.get(validador));
                allValid = false;
                break; // Detenerse en el primer error
            }
        }
        
        return allValid;
    }

    private void mostrarAdv(JLabel lb) {
        lb.setText("*"); // Color rojo para mayor visibilidad
        lb.setVisible(true);

    }

    private void limpiarWarnings() {
        lbWarningProjectName.setText("");
        lbWarningOverView.setText("");
        lbWarningDescription.setText("");
        lbWarningObjetive.setText("");
        lbWarningMaximumTime.setText("");
        lbWarningEstimatedBudge.setText("");
        lbWarningEstimatedDeliveryDate.setText("");
    }
     private void configurarValidadores() {
        Validator nombreComposite = new Validator();
        nombreComposite.addStrategy(new NotEmptyAndNotDefaultStrategy("project name", "Nombre del proyecto"));
        this.nombreValidator = new ValidationContext(nombreComposite);
        
        Validator resumenComposite = new Validator();
        resumenComposite.addStrategy(new NotEmptyAndNotDefaultStrategy("overView", "Resumen"));
        this.resumenValidator = new ValidationContext(resumenComposite);

        Validator descripcionComposite = new Validator();
        descripcionComposite.addStrategy(new NotEmptyAndNotDefaultStrategy("description", "Descripción"));
        this.descripcionValidator = new ValidationContext(descripcionComposite);

        Validator objetivoComposite = new Validator();
        objetivoComposite.addStrategy(new NotEmptyAndNotDefaultStrategy("objective", "Objetivo"));
        this.objetivoValidator = new ValidationContext(objetivoComposite);

        Validator tiempoComposite = new Validator();
        tiempoComposite.addStrategy(new NotEmptyAndNotDefaultStrategy("maximum time", "Tiempo máximo"));
        this.tiempoValidator = new ValidationContext(tiempoComposite);

        Validator presupuestoComposite = new Validator();
        presupuestoComposite.addStrategy(new NotEmptyAndNotDefaultStrategy("estimated budget", "Presupuesto"));
        presupuestoComposite.addStrategy(new NumericDecimalValidationStrategy());
        this.presupuestoValidator = new ValidationContext(presupuestoComposite);

        Validator fechaComposite = new Validator();
        fechaComposite.addStrategy(new NotEmptyAndNotDefaultStrategy("estimated delivery date", "Fecha de entrega"));
        fechaComposite.addStrategy(new DateValidationStrategy("dd/MM/yyyy"));
        this.fechaValidator = new ValidationContext(fechaComposite);
    }
    private void txtNameProyectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameProyectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameProyectActionPerformed

    private void txtObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObjetivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarProyecto;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbEstimatedBudge;
    private javax.swing.JLabel lbEstimatedDeliveryDate;
    private javax.swing.JLabel lbMaximumTime;
    private javax.swing.JLabel lbObjetive;
    private javax.swing.JLabel lbOverView;
    private javax.swing.JLabel lbProjectName;
    private javax.swing.JLabel lbWarningDescription;
    private javax.swing.JLabel lbWarningEstimatedBudge;
    private javax.swing.JLabel lbWarningEstimatedDeliveryDate;
    private javax.swing.JLabel lbWarningMaximumTime;
    private javax.swing.JLabel lbWarningObjetive;
    private javax.swing.JLabel lbWarningOverView;
    private javax.swing.JLabel lbWarningProjectName;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtEstimatedBudge;
    private javax.swing.JTextField txtMaximumTime;
    private javax.swing.JTextField txtNameProyect;
    private javax.swing.JTextField txtObjetivo;
    private javax.swing.JTextField txtOverView;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextField txteEstimatedDeliveryDate;
    // End of variables declaration//GEN-END:variables
}
