# application.yml para StudentMicroservice
spring:
  application:
    name: StudentMicroservice

  # Configuración H2 Database
  h2:
    console:
      enabled: true       # Activar consola web
      path: /h2-console   # Ruta de acceso

  datasource:
    url: jdbc:h2:mem:studentdb  # Nombre de la BD específica
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update    # Actualizar esquema automáticamente

  # Configuración RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083  # Puerto del microservicio

#  Configuración de seguridad JWT (si aplica)
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/MicroserviceSPM
        jwk-set-uri: http://localhost:8080/realms/MicroserviceSPM/protocol/openid-connect/certs