# application.yml - Microservicio de Postulación
spring:
  application:
    name: MicroServicePostulation

  # Configuración de H2 Database
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  # Configuración de RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082  # Puerto específico para postulaciones

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/MicroserviceSPM
        jwk-set-uri: http://localhost:8080/realms/MicroserviceSPM/protocol/openid-connect/certs