spring:
  application:
    name: MicroServicePostulation

  # Configuración PostgreSQL
  datasource:
    url: jdbc:postgresql://postgres-postulation:5432/postulationdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Configuración RabbitMQ
  rabbitmq:
    host: rabbitmq  # Nombre del servicio en Docker
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

# Configuración Keycloak
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://keycloak:8080/realms/MicroserviceSPM
        jwk-set-uri: http://keycloak:8080/realms/MicroserviceSPM/protocol/openid-connect/certs